### ISSUE TITLE
StorageUnknownError: fetch failed | NestJS

### ISSUE THREAD

**Issue by karrtopelka** [supabase/storage-js#161]
Hello, I am trying to upload an image to existing public bucket
```typescript
async updateAvatar(file: Express.Multer.File) {
    const { originalname, mimetype, buffer } = file;

    const { data, error } = await this.storage
      .from('avatars')
      .upload(`public/${originalname}`, buffer, {
        contentType: mimetype,
        upsert: false,
      });

    if (error) {
      throw new Error(error.message);
    }

    return data;
  }
```

But getting error:
```bash
{
  data: null,
  error: StorageUnknownError: fetch failed
      at /Users/karrtopelka/Documents/business_idea/proposal/server/node_modules/@supabase/storage-js/src/lib/fetch.ts:32:12
      at Generator.next (<anonymous>)
      at fulfilled (/Users/karrtopelka/Documents/business_idea/proposal/server/node_modules/@supabase/storage-js/dist/main/lib/fetch.js:5:58)
      at processTicksAndRejections (node:internal/process/task_queues:95:5) {
    __isStorageError: true,
    originalError: TypeError: fetch failed
        at Object.fetch (node:internal/deps/undici/undici:14294:11)
        at processTicksAndRejections (node:internal/process/task_queues:95:5) {
      cause: [Error]
    }
  }
}
```

Here is my service:
```typescript
import { Injectable } from '@nestjs/common';
import { StorageClient } from '@supabase/storage-js';

@Injectable()
export class SupabaseService extends StorageClient {
  constructor() {
    super(process.env.STORAGE_URL, {
      apikey: process.env.API_SECRET,
      Authorization: `Bearer ${process.env.API_SECRET}`,
    });
  }
}
```

What can be the issue?
Found unanswered question but with svelte: [https://github.com/supabase/supabase/discussions/12389_](click)

**Comment by FinesseLineUp** [comment]
receive the same error for all supabase.storage requests in Expo app: stack: "StorageUnknownError: Network request failed\n    at construct (native)\n    at apply (native)\n    at _construct (http://192.168.0.103:19000/node_modules/expo/

**Comment by VCasecnikovs** [comment]
I have solved this problem for myself:

The problem happens, when I send File to Supabase Storage.

To solve the problem, I send Array Buffer:
```
let array_buffer = await image.arrayBuffer();
```
